### ISSUE TITLE
Coverage data not found

### ISSUE THREAD

**Issue by bardic** [appsquickly/frankencover.it#32]
Hey all,
This was all working a few months ago for me but has recently stopped and keeps throwing :

```
▸ Code Coverage ******/
Caught: java.lang.RuntimeException:

✗ Coverage data not found
    ☐ To see how to set build flags, visit http://frankencover.it
    ☐ Exercise your code with tests or otherwise.
    ☐ Run this script again.


java.lang.RuntimeException:

✗ Coverage data not found
    ☐ To see how to set build flags, visit http://frankencover.it
    ☐ Exercise your code with tests or otherwise.
    ☐ Run this script again.


	at ReportParser.<init>(with:220)
	at ReportGenerator.printSummary(with:174)
	at ReportGenerator.generate(with:160)
	at ReportGenerator$generate.call(Unknown Source)
	at FrankenCliReader.execute(with:59)
	at FrankenCliReader$execute.call(Unknown Source)
	at with.run(with:15)
```

I'm using XCode 7.2.1 and lcov 1.12

**Comment by jasperblues** [comment]
Can you run with the debug flag?

**Comment by xxKRASHxx** [comment]
The similar problem

▸ Code Coverage /Users/KRASH/SigmaSoftware/1CMC/
mkdir -p build/reports/temp/coverage-data-collate
mkdir -p build/reports/temp/coverage-data
mkdir -p /Users/KRASH/SigmaSoftware/1CMC/build/reports/coverage/data
find ~/Library/Developer/Xcode/DerivedData  -name NSError+SSError.gcno -o -name NSError+SSError.gcda -o -name SSConstants.gcno -o -name SSConstants.gcda -o -name SSDemandControllerManager.gcno -o -name SSDemandControllerManager.gcda -o -name SSGlobalNetworkSettings.gcno -o -name SSGlobalNetworkSettings.gcda -o -name SSKeyChainUtil.gcno -o -name SSKeyChainUtil.gcda -o -name SSDictionaryBuilder.gcno -o -name SSDictionaryBuilder.gcda -o -name SSRestDictionaryBuilder.gcno -o -name SSRestDictionaryBuilder.gcda -o -name SSDemandParser.gcno -o -name SSDemandParser.gcda -o -name SSParser.gcno -o -name SSParser.gcda -o -name SSResponseParser.gcno -o -name SSResponseParser.gcda -o -name SSDemandService.gcno -o -name SSDemandService.gcda -o -name SSLinkHandlerService.gcno -o -name SSLinkHandlerService.gcda -o -name SSLoginService.gcno -o -name SSLoginService.gcda -o -name SSPushHandlerService.gcno -o -name SSPushHandlerService.gcda -o -name SSUpdaterService.gcno -o -name SSUpdaterService.gcda -o -name SSUserService.gcno -o -name SSUserService.gcda -o -name SSServiceLayer.gcno -o -name SSServiceLayer.gcda -o -name SSServiceClient+Auth.gcno -o -name SSServiceClient+Auth.gcda -o -name SSServiceClient.gcno -o -name SSServiceClient.gcda -o -name SSCostsData.gcno -o -name SSCostsData.gcda -o -name SSCurrency.gcno -o -name SSCurrency.gcda -o -name SSDemandData.gcno -o -name SSDemandData.gcda -o -name SSReportData.gcno -o -name SSReportData.gcda -o -name SSRequestData.gcno -o -name SSRequestData.gcda -o -name SSResponce.gcno -o -name SSResponce.gcda -o -name SSResponse.gcno -o -name SSResponse.gcda -o -name SSReviewerData.gcno -o -name SSReviewerData.gcda -o -name SSLeftAligmentButton.gcno -o -name SSLeftAligmentButton.gcda -o -name SSCenterSegue.gcno -o -name SSCenterSegue.gcda -o -name SSLoginSegue.gcno -o -name SSLoginSegue.gcda -o -name SSUnwindLoginSegue.gcno -o -name SSUnwindLoginSegue.gcda -o -name SSDynamicCollectionView.gcno -o -name SSDynamicCollectionView.gcda -o -name SSTriangleButton.gcno -o -name SSTriangleButton.gcda -o -name SSApproverViewCell.gcno -o -name SSApproverViewCell.gcda -o -name SSDemandDetailsCollectionViewCell.gcno -o -name SSDemandDetailsCollectionViewCell.gcda -o -name SSDemandDetailsTableViewCell.gcno -o -name SSDemandDetailsTableViewCell.gcda -o -name SSDemandTableViewCell.gcno -o -name SSDemandTableViewCell.gcda -o -name SSMenuTableViewCell.gcno -o -name SSMenuTableViewCell.gcda -o -name SSTriangleButton.gcno -o -name SSTriangleButton.gcda -o -name CALayer+SSLayer.gcno -o -name CALayer+SSLayer.gcda -o -name UIColor+SSColor.gcno -o -name UIColor+SSColor.gcda -o -name SSCostView.gcno -o -name SSCostView.gcda -o -name SSDemandView.gcno -o -name SSDemandView.gcda -o -name SSProjectCategoryView.gcno -o -name SSProjectCategoryView.gcda -o -name SSProjectImageView.gcno -o -name SSProjectImageView.gcda -o -name SSReviewerStatusImageView.gcno -o -name SSReviewerStatusImageView.gcda -o -name SSWindow.gcno -o -name SSWindow.gcda -o -name SSActivityIndicatorViewController.gcno -o -name SSActivityIndicatorViewController.gcda -o -name SSApproveViewController.gcno -o -name SSApproveViewController.gcda -o -name SSCompletionViewController.gcno -o -name SSCompletionViewController.gcda -o -name SSRejectViewController.gcno -o -name SSRejectViewController.gcda -o -name SSDemandDetailsViewController.gcno -o -name SSDemandDetailsViewController.gcda -o -name SSDemandViewController.gcno -o -name SSDemandViewController.gcda -o -name SSLoginViewController.gcno -o -name SSLoginViewController.gcda -o -name SSMenuListViewController.gcno -o -name SSMenuListViewController.gcda -o -name SSRootViewController.gcno -o -name SSRootViewController.gcda -o -name SSApprovedTutorialViewController.gcno -o -name SSApprovedTutorialViewController.gcda -o -name SSFinishTutorialViewController.gcno -o -name SSFinishTutorialViewController.gcda -o -name SSRejectTutorialViewController.gcno -o -name SSRejectTutorialViewController.gcda -o -name SSTapTutorialViewController.gcno -o -name SSTapTutorialViewController.gcda -o -name SSTutorialPageViewController.gcno -o -name SSTutorialPageViewController.gcda -o -name SSTutorialTableViewController.gcno -o -name SSTutorialTableViewController.gcda -o -name SSTutorialView.gcno -o -name SSTutorialView.gcda -o -name SSTutorialViewController.gcno -o -name SSTutorialViewController.gcda -o -name UIViewController+SSAlertController.gcno -o -name UIViewController+SSAlertController.gcda -o -name SSApproversCollectionViewProvider.gcno -o -name SSApproversCollectionViewProvider.gcda -o -name SSDemandCollectionViewProvider.gcno -o -name SSDemandCollectionViewProvider.gcda -o -name SSDemandDetailsTableViewProvider.gcno -o -name SSDemandDetailsTableViewProvider.gcda -o -name SSDemandTableViewProvider.gcno -o -name SSDemandTableViewProvider.gcda -o -name SSMenuViewProvider.gcno -o -name SSMenuViewProvider.gcda -o -name SSPageViewControllerProvider.gcno -o -name SSPageViewControllerProvider.gcda -o -name SSAppDelegate.gcno -o -name SSAppDelegate.gcda -o -name SSApplication.gcno -o -name SSApplication.gcda -o -name NSURL+QueryDictionary.gcno -o -name NSURL+QueryDictionary.gcda -o -name YRActivityIndicator.gcno -o -name YRActivityIndicator.gcda -o -name FXReachability.gcno -o -name FXReachability.gcda -o -name FXReachability.gcno -o -name FXReachability.gcda -o -name FXReachability.gcno -o -name FXReachability.gcda -o -name SSServerSettings.gcno -o -name SSServerSettings.gcda -o -name AFHTTPSessionManager.gcno -o -name AFHTTPSessionManager.gcda -o -name AFNetworking.gcno -o -name AFNetworking.gcda -o -name AFNetworkReachabilityManager.gcno -o -name AFNetworkReachabilityManager.gcda -o -name AFSecurityPolicy.gcno -o -name AFSecurityPolicy.gcda -o -name AFURLRequestSerialization.gcno -o -name AFURLRequestSerialization.gcda -o -name AFURLResponseSerialization.gcno -o -name AFURLResponseSerialization.gcda -o -name AFURLSessionManager.gcno -o -name AFURLSessionManager.gcda -o -name AFAutoPurgingImageCache.gcno -o -name AFAutoPurgingImageCache.gcda -o -name AFImageDownloader.gcno -o -name AFImageDownloader.gcda -o -name AFNetworkActivityIndicatorManager.gcno -o -name AFNetworkActivityIndicatorManager.gcda -o -name UIActivityIndicatorView+AFNetworking.gcno -o -name UIActivityIndicatorView+AFNetworking.gcda -o -name UIButton+AFNetworking.gcno -o -name UIButton+AFNetworking.gcda -o -name UIImage+AFNetworking.gcno -o -name UIImage+AFNetworking.gcda -o -name UIImageView+AFNetworking.gcno -o -name UIImageView+AFNetworking.gcda -o -name UIKit+AFNetworking.gcno -o -name UIKit+AFNetworking.gcda -o -name UIProgressView+AFNetworking.gcno -o -name UIProgressView+AFNetworking.gcda -o -name UIRefreshControl+AFNetworking.gcno -o -name UIRefreshControl+AFNetworking.gcda -o -name UIWebView+AFNetworking.gcno -o -name UIWebView+AFNetworking.gcda -o -name AFAutoPurgingImageCache.gcno -o -name AFAutoPurgingImageCache.gcda -o -name AFHTTPSessionManager.gcno -o -name AFHTTPSessionManager.gcda -o -name AFImageDownloader.gcno -o -name AFImageDownloader.gcda -o -name AFNetworkActivityIndicatorManager.gcno -o -name AFNetworkActivityIndicatorManager.gcda -o -name AFNetworking.gcno -o -name AFNetworking.gcda -o -name AFNetworkReachabilityManager.gcno -o -name AFNetworkReachabilityManager.gcda -o -name AFSecurityPolicy.gcno -o -name AFSecurityPolicy.gcda -o -name AFURLRequestSerialization.gcno -o -name AFURLRequestSerialization.gcda -o -name AFURLResponseSerialization.gcno -o -name AFURLResponseSerialization.gcda -o -name AFURLSessionManager.gcno -o -name AFURLSessionManager.gcda -o -name UIActivityIndicatorView+AFNetworking.gcno -o -name UIActivityIndicatorView+AFNetworking.gcda -o -name UIButton+AFNetworking.gcno -o -name UIButton+AFNetworking.gcda -o -name UIImage+AFNetworking.gcno -o -name UIImage+AFNetworking.gcda -o -name UIImageView+AFNetworking.gcno -o -name UIImageView+AFNetworking.gcda -o -name UIKit+AFNetworking.gcno -o -name UIKit+AFNetworking.gcda -o -name UIProgressView+AFNetworking.gcno -o -name UIProgressView+AFNetworking.gcda -o -name UIRefreshControl+AFNetworking.gcno -o -name UIRefreshControl+AFNetworking.gcda -o -name UIWebView+AFNetworking.gcno -o -name UIWebView+AFNetworking.gcda -o -name JTHamburgerButton.gcno -o -name JTHamburgerButton.gcda -o -name LGSideMenuController.gcno -o -name LGSideMenuController.gcda -o -name MCSwipeTableViewCell.gcno -o -name MCSwipeTableViewCell.gcda -o -name MMDrawerBarButtonItem.gcno -o -name MMDrawerBarButtonItem.gcda -o -name MMDrawerController+Subclass.gcno -o -name MMDrawerController+Subclass.gcda -o -name MMDrawerController.gcno -o -name MMDrawerController.gcda -o -name MMDrawerVisualState.gcno -o -name MMDrawerVisualState.gcda -o -name UIViewController+MMDrawerController.gcno -o -name UIViewController+MMDrawerController.gcda -o -name RBStoryboardLink.gcno -o -name RBStoryboardLink.gcda -o -name RBStoryboardLinkSource.gcno -o -name RBStoryboardLinkSource.gcda -o -name RBStoryboardModalSegue.gcno -o -name RBStoryboardModalSegue.gcda -o -name RBStoryboardPopoverSegue.gcno -o -name RBStoryboardPopoverSegue.gcda -o -name RBStoryboardPushSegue.gcno -o -name RBStoryboardPushSegue.gcda -o -name RBStoryboardSegue.gcno -o -name RBStoryboardSegue.gcda -o -name UIViewController+RBStoryboardLink.gcno -o -name UIViewController+RBStoryboardLink.gcda -o -name UICollectionViewLeftAlignedLayout.gcno -o -name UICollectionViewLeftAlignedLayout.gcda -o -name JTHamburgerButton.gcno -o -name JTHamburgerButton.gcda -o -name LGSideMenuController.gcno -o -name LGSideMenuController.gcda -o -name MCSwipeTableViewCell.gcno -o -name MCSwipeTableViewCell.gcda -o -name MMDrawerBarButtonItem.gcno -o -name MMDrawerBarButtonItem.gcda -o -name MMDrawerController+Subclass.gcno -o -name MMDrawerController+Subclass.gcda -o -name MMDrawerController.gcno -o -name MMDrawerController.gcda -o -name MMDrawerVisualState.gcno -o -name MMDrawerVisualState.gcda -o -name UIViewController+MMDrawerController.gcno -o -name UIViewController+MMDrawerController.gcda -o -name RBStoryboardLink.gcno -o -name RBStoryboardLink.gcda -o -name RBStoryboardLinkSource.gcno -o -name RBStoryboardLinkSource.gcda -o -name RBStoryboardModalSegue.gcno -o -name RBStoryboardModalSegue.gcda -o -name RBStoryboardPopoverSegue.gcno -o -name RBStoryboardPopoverSegue.gcda -o -name RBStoryboardPushSegue.gcno -o -name RBStoryboardPushSegue.gcda -o -name RBStoryboardSegue.gcno -o -name RBStoryboardSegue.gcda -o -name UIViewController+RBStoryboardLink.gcno -o -name UIViewController+RBStoryboardLink.gcda -o -name AFNetworking-umbrella.gcno -o -name AFNetworking-umbrella.gcda -o -name JTHamburgerButton-umbrella.gcno -o -name JTHamburgerButton-umbrella.gcda -o -name LGSideMenuController-umbrella.gcno -o -name LGSideMenuController-umbrella.gcda -o -name MCSwipeTableViewCell-umbrella.gcno -o -name MCSwipeTableViewCell-umbrella.gcda -o -name MMDrawerController-umbrella.gcno -o -name MMDrawerController-umbrella.gcda -o -name Pods-1CMC-umbrella.gcno -o -name Pods-1CMC-umbrella.gcda -o -name Pods-CMCIntegrationTests-umbrella.gcno -o -name Pods-CMCIntegrationTests-umbrella.gcda -o -name RBStoryboardLink-umbrella.gcno -o -name RBStoryboardLink-umbrella.gcda -o -name UICollectionViewLeftAlignedLayout-umbrella.gcno -o -name UICollectionViewLeftAlignedLayout-umbrella.gcda -o -name UICollectionViewLeftAlignedLayout.gcno -o -name UICollectionViewLeftAlignedLayout.gcda | rsync --files-from=- / build/reports/temp/coverage-data-collate
find build/reports/temp/coverage-data-collate -type file -exec cp -fr {} build/reports/temp/coverage-data \;
rm -fr build/reports/temp/coverage-data-collate
geninfo build/reports/temp/coverage-data/*.gcno --no-recursion --output-filename build/reports/temp/coverage.info.temp
lcov -r build/reports/temp/coverage.info.temp main.m queue.h once.h CGGeometry.h MKGeometry.h NSRange.h > build/reports/temp/coverage.info        
genhtml -o /Users/KRASH/SigmaSoftware/1CMC/build/reports/coverage --prefix /Users/KRASH/SigmaSoftware/1CMC/ build/reports/temp/coverage.info 		
cp -R build/reports/temp/* /Users/KRASH/SigmaSoftware/1CMC/build/reports/coverage/data
            
Caught: java.lang.RuntimeException: 

✗ Coverage data not found
    ☐ To see how to set build flags, visit http://frankencover.it
    ☐ Exercise your code with tests or otherwise.
    ☐ Run this script again.


java.lang.RuntimeException: 

✗ Coverage data not found
    ☐ To see how to set build flags, visit http://frankencover.it
    ☐ Exercise your code with tests or otherwise.
    ☐ Run this script again.


	at ReportParser.<init>(with:220)
	at ReportGenerator.printSummary(with:174)
	at ReportGenerator.generate(with:160)
	at ReportGenerator$generate.call(Unknown Source)
	at FrankenCliReader.execute(with:59)
	at FrankenCliReader$execute.call(Unknown Source)
	at with.run(with:15)

**Comment by jasperblues** [comment]
@xxKRASHxx Have you set up your .xcodeproj to generate coverage? This is a manual step. Details in the guide.

**Comment by Guziq** [comment]
@xxKRASHxx I have the same error - I've followed the guide.

**Comment by jasperblues** [comment]
@Guziq Can you please run with the debug (`--debug`) flag?

**Comment by Guziq** [comment]
@jasperblues 

```
mkdir -p build/reports/temp/coverage-data-collate
mkdir -p build/reports/temp/coverage-data
mkdir -p /Users/guzik/W86BP4NY3US9CN/build/reports/coverage/data
find ~/Library/Developer/Xcode/DerivedData   | rsync --files-from=- / build/reports/temp/coverage-data-collate
find build/reports/temp/coverage-data-collate -type file -exec cp -fr {} build/reports/temp/coverage-data \;
rm -fr build/reports/temp/coverage-data-collate
geninfo build/reports/temp/coverage-data/*.gcno --no-recursion --output-filename build/reports/temp/coverage.info.temp
lcov -r build/reports/temp/coverage.info.temp main.m queue.h once.h CGGeometry.h MKGeometry.h NSRange.h > build/reports/temp/coverage.info
genhtml -o /Users/guzik/W86BP4NY3US9CN/build/reports/coverage --prefix /Users/guzik/W86BP4NY3US9CN/AidappiOS/ build/reports/temp/coverage.info
cp -R build/reports/temp/* /Users/guzik/W86BP4NY3US9CN/build/reports/coverage/data

Caught: java.lang.RuntimeException:

✗ Coverage data not found
    ☐ To see how to set build flags, visit http://frankencover.it
    ☐ Exercise your code with tests or otherwise.
    ☐ Run this script again.


java.lang.RuntimeException:

✗ Coverage data not found
    ☐ To see how to set build flags, visit http://frankencover.it
    ☐ Exercise your code with tests or otherwise.
    ☐ Run this script again.


	at ReportParser.<init>(with:220)
	at ReportGenerator.printSummary(with:174)
	at ReportGenerator.generate(with:160)
	at ReportGenerator$generate.call(Unknown Source)
	at FrankenCliReader.execute(with:59)
	at FrankenCliReader$execute.call(Unknown Source)
	at with.run(with:15)
```

**Comment by jasperblues** [comment]
@Guziq hmm, not finding coverage output. You definitely set the build flags of your _application_ target in Xcode?

**Comment by Guziq** [comment]
![image](https://user-images.githubusercontent.com/2957113/30318384-413a36c0-97ad-11e7-983a-1ac0bed85507.png)

and also

![image](https://user-images.githubusercontent.com/2957113/30318420-578ec3fa-97ad-11e7-8484-e73994e43215.png)

probably this is not needed:

![image](https://user-images.githubusercontent.com/2957113/30318679-14171252-97ae-11e7-94b4-5b489d615730.png)

I have just one target. I know its a lot to ask, but maybe you would be able to create an example project?

**Comment by jasperblues** [comment]
https://github.com/appsquickly/Typhoon uses http://frankencover.it (actually we now use Travis for the CI builds). 

Sorry, I just noticed the error you're seeing. Likely the coverage output from Xcode has moved (again). Fixing, will report back soon.

**Comment by jasperblues** [comment]
@bardic @Guziq 

**To Make Things Work**

```sh
git clone https://github.com/linux-test-project/lcov.git
cd lcov
sudo make install
```

**Confirm:**
`lcov --version` gives version 1.13 _not_ 1.12

Then all will be well. 

**Sample Project**

```
clone https://github.com/appsquickly/Typhoon
run ./build.sh
```

Sorry about the error. I'll make a note to update details on the website tomorrow.

**Comment by Guziq** [comment]
@Guziq That's unfortunate, as I have lcov 1.13

```
MacBook-Pro-2:~ guzik$ lcov --version
lcov: LCOV version 1.13
```

**Comment by jasperblues** [comment]
@Guziq Maybe it is in fact bleeding edge, that is required. I reproduced the error and fixed with: 

```
git clone https://github.com/linux-test-project/lcov.git
cd lcov
sudo make install
```

Then confirm `lcov --version` output is `lcov: LCOV version 1.13-11-gb6a1136`. Doing this and then running on the sample project (Typhoon) , solves the issue. 

Can you please try.

**Comment by Guziq** [comment]
@jasperblues

Pretty strange, everything works with https://github.com/appsquickly/Typhoon.

It seems like the script has troubles with finding correct coverage data in DerivedData, as I've created empty project (yet configured), did run the script and got stats from Typhoon:

```
MacBook-Pro-2:test guzik$ groovy http://frankencover.it/with -source-dir test

▸ Code Coverage test/
    ✓ lines........: 89.8% (8788 of 9789 lines)
   📊  full report..: build/reports/coverage/index.html
```

**Comment by jasperblues** [comment]
Can you do `find ~ -name "*.gcda"` and look for coverage files related to your project? 

With Typhoon, I got an error that looked like 'Coverage Data Not Found` - this is what the tool reported at least. In fact it was failing at the geninfo step of the following: 

```groovy
 def script = """\
            |mkdir -p ${escapeSpecialCharacters(collationDir)}
            |mkdir -p ${escapeSpecialCharacters(coverageData)}
			|mkdir -p ${escapeSpecialCharacters(reportLocation.absolutePath)}/data
            |find ${escapeSpecialCharacters(ideConfig.searchDirectories())} ${reportConfig.dataFileNames()} | rsync --files-from=- / ${escapeSpecialCharacters(collationDir)}
            |find ${escapeSpecialCharacters(collationDir)} -type file -exec cp -fr {} ${escapeSpecialCharacters(coverageData)} \\;
            |rm -fr ${escapeSpecialCharacters(collationDir)}
            |geninfo ${escapeSpecialCharacters(coverageData)}/*.gcno --no-recursion --output-filename ${escapeSpecialCharacters(coverageInfoFile)}.temp
            |lcov -r ${escapeSpecialCharacters(coverageInfoFile)}.temp ${excludeSymbols} > ${escapeSpecialCharacters(coverageInfoFile)}        
			|${genHtmlCmd} 		
            |cp -R ${escapeSpecialCharacters(tempDir)}/* ${escapeSpecialCharacters(reportLocation.absolutePath)}/data
            """.stripMargin()	
```

- .gcda and .gcno files were correctly collated into the local build dir
- Running geninfo on them failed (.bb file not found) due to incompatibility of the output produced by Xcode. 

Sounds like something else is failing in your case. Are you able to share a failing project?

**Comment by jasperblues** [comment]
Btw, step above for Typhoon: 

```
groovy http://frankencover.it/with -source-dir test
```

It should actually be: 

```groovy
groovy http://frankencover.it/with -source-dir Source/
```

^-- don't know why the former still worked.

**Comment by Guziq** [comment]
> Btw, step above for Typhoon:

I know, but that was the step invoked on my test project (called **test** with source located in **test/** dir) and yet the script picked the Typhoon for analysis.

The `find ~ -name "*.gcda"` finds the:

```
/Users/guzik/Library/Developer/Xcode/DerivedData/test-hfuuoriyckllpzgmrltgugpnxmft/Build/Intermediates/CodeCoverage/Intermediates/test.build/Debug-iphonesimulator/test.build/Objects-normal/x86_64/test.gcda
(...)
/Users/guzik/Library/Developer/Xcode/DerivedData/Typhoon-bhfbnyjasgxkycdwwmaosyqseycv/Build/Intermediates/CodeCoverage/Intermediates/Typhoon.build/Debug-iphonesimulator/Typhoon-iOS.build/Objects-normal/x86_64/CavalryMan.gcda
(...)
```

I can share this project, but it's just an empty one, generated from Xcode (with _enabled testability_, _shared scheme_ and _generated legacy test coverage files_.

**Comment by jasperblues** [comment]
> I know, but that was the step invoked on my test project (called test with source located in test/ dir) and yet the script picked the Typhoon for analysis.

Oh!? Something not right. 

Sure, if you have a project that reproduces the error, I can troubleshoot for you.

**Comment by Guziq** [comment]
I've added you to the project (Bitbucket)

**Comment by jasperblues** [comment]
Thanks. I just have to finish some billable work, then will look tonight. (GMT+8)

**Comment by jasperblues** [comment]
Really sorry - still haven't gotten to this. Promise to look soon.

**Comment by Guziq** [comment]
@jasperblues no worries :) !

**Comment by jasperblues** [comment]
😊 So (four years later) looks like the issue is too many input source files. For folks still using this - will see if I can fix it. Also looks like we can have Swift support now.
