### ISSUE TITLE
Coverage data not found

### ISSUE THREAD

**Issue by keithkml** [appsquickly/frankencover.it#9]
I enabled the two build settings (coverage & instrumentation) in Xcode, and am trying to run frankencover, but getting an error message.

```
Keiths-MBP-2:glue keith$ groovy http://frankencover.it/with -source-dir src/ios/objc/

▸ Code Coverage src/ios/objc/
Caught: java.lang.RuntimeException: 

✗ Coverage data not found
    ☐ To see how to set build flags, visit http://frankencover.it
    ☐ Exercise your code with tests or otherwise.
    ☐ Run this script again.


java.lang.RuntimeException: 

✗ Coverage data not found
    ☐ To see how to set build flags, visit http://frankencover.it
    ☐ Exercise your code with tests or otherwise.
    ☐ Run this script again.


	at ReportParser.<init>(with:203)
	at ReportGenerator.printSummary(with:166)
	at ReportGenerator.generate(with:153)
	at ReportGenerator$generate.call(Unknown Source)
	at FrankenCliReader.execute(with:62)
	at FrankenCliReader$execute.call(Unknown Source)
	at with.run(with:13)
```

I've included this to show you that Xcode is indeed generating the coverage & instrumentation files:

```
Keiths-MBP-2:glue keith$ find . -name \*.gcno
./demo/glue-ios/DerivedData/GlueDemo/Build/Intermediates/Glue.build/Debug-iphonesimulator/Glue.build/Objects-normal/i386/Camera.gcno
./demo/glue-ios/DerivedData/GlueDemo/Build/Intermediates/Glue.build/Debug-iphonesimulator/Glue.build/Objects-normal/i386/FlashBrightnessHandler.gcno
./demo/glue-ios/DerivedData/GlueDemo/Build/Intermediates/Glue.build/Debug-iphonesimulator/Glue.build/Objects-normal/i386/Glue-objc.gcno
./demo/glue-ios/DerivedData/GlueDemo/Build/Intermediates/Glue.build/Debug-iphonesimulator/Glue.build/Objects-normal/i386/Glue.gcno
./demo/glue-ios/DerivedData/GlueDemo/Build/Intermediates/Glue.build/Debug-iphonesimulator/Glue.build/Objects-normal/i386/GlueImpl.gcno
./demo/glue-ios/DerivedData/GlueDemo/Build/Intermediates/Glue.build/Debug-iphonesimulator/Glue.build/Objects-normal/i386/mongoose.gcno
./demo/glue-ios/DerivedData/GlueDemo/Build/Intermediates/Glue.build/Debug-iphonesimulator/Glue.build/Objects-normal/i386/WCWebViewController.gcno
./demo/glue-ios/DerivedData/GlueDemo/Build/Intermediates/Glue.build/Debug-iphonesimulator/Glue.build/Objects-normal/x86_64/Camera.gcno
./demo/glue-ios/DerivedData/GlueDemo/Build/Intermediates/Glue.build/Debug-iphonesimulator/Glue.build/Objects-normal/x86_64/FlashBrightnessHandler.gcno
./demo/glue-ios/DerivedData/GlueDemo/Build/Intermediates/Glue.build/Debug-iphonesimulator/Glue.build/Objects-normal/x86_64/Glue-objc.gcno
./demo/glue-ios/DerivedData/GlueDemo/Build/Intermediates/Glue.build/Debug-iphonesimulator/Glue.build/Objects-normal/x86_64/Glue.gcno
./demo/glue-ios/DerivedData/GlueDemo/Build/Intermediates/Glue.build/Debug-iphonesimulator/Glue.build/Objects-normal/x86_64/GlueImpl.gcno
./demo/glue-ios/DerivedData/GlueDemo/Build/Intermediates/Glue.build/Debug-iphonesimulator/Glue.build/Objects-normal/x86_64/mongoose.gcno
./demo/glue-ios/DerivedData/GlueDemo/Build/Intermediates/Glue.build/Debug-iphonesimulator/Glue.build/Objects-normal/x86_64/WCWebViewController.gcno
./demo/glue-ios/DerivedData/GlueDemo/Build/Intermediates/Glue.build/Debug-iphonesimulator/GlueTests.build/Objects-normal/i386/AFHTTPRequestOperation.gcno
./demo/glue-ios/DerivedData/GlueDemo/Build/Intermediates/Glue.build/Debug-iphonesimulator/GlueTests.build/Objects-normal/i386/AFHTTPRequestOperationManager.gcno
./demo/glue-ios/DerivedData/GlueDemo/Build/Intermediates/Glue.build/Debug-iphonesimulator/GlueTests.build/Objects-normal/i386/AFHTTPSessionManager.gcno
./demo/glue-ios/DerivedData/GlueDemo/Build/Intermediates/Glue.build/Debug-iphonesimulator/GlueTests.build/Objects-normal/i386/AFNetworkReachabilityManager.gcno
./demo/glue-ios/DerivedData/GlueDemo/Build/Intermediates/Glue.build/Debug-iphonesimulator/GlueTests.build/Objects-normal/i386/AFSecurityPolicy.gcno
./demo/glue-ios/DerivedData/GlueDemo/Build/Intermediates/Glue.build/Debug-iphonesimulator/GlueTests.build/Objects-normal/i386/AFURLConnectionOperation.gcno
./demo/glue-ios/DerivedData/GlueDemo/Build/Intermediates/Glue.build/Debug-iphonesimulator/GlueTests.build/Objects-normal/i386/AFURLRequestSerialization.gcno
./demo/glue-ios/DerivedData/GlueDemo/Build/Intermediates/Glue.build/Debug-iphonesimulator/GlueTests.build/Objects-normal/i386/AFURLResponseSerialization.gcno
./demo/glue-ios/DerivedData/GlueDemo/Build/Intermediates/Glue.build/Debug-iphonesimulator/GlueTests.build/Objects-normal/i386/AFURLSessionManager.gcno
./demo/glue-ios/DerivedData/GlueDemo/Build/Intermediates/Glue.build/Debug-iphonesimulator/GlueTests.build/Objects-normal/i386/GUHTTPTest.gcno
./demo/glue-ios/DerivedData/GlueDemo/Build/Intermediates/Glue.build/Debug-iphonesimulator/GlueTests.build/Objects-normal/i386/GUHTTPTestResponse.gcno
./demo/glue-ios/DerivedData/GlueDemo/Build/Intermediates/Glue.build/Debug-iphonesimulator/GlueTests.build/Objects-normal/i386/GUServerTests.gcno
./demo/glue-ios/DerivedData/GlueDemo/Build/Intermediates/Glue.build/Debug-iphonesimulator/GlueTests.build/Objects-normal/i386/ServerTestCase.gcno
./demo/glue-ios/DerivedData/GlueDemo/Build/Intermediates/Glue.build/Debug-iphonesimulator/GlueTests.build/Objects-normal/i386/WebViewTestCase.gcno
./demo/glue-ios/DerivedData/GlueDemo/Build/Intermediates/Glue.build/Debug-iphonesimulator/GlueTests.build/Objects-normal/x86_64/AFHTTPRequestOperation.gcno
./demo/glue-ios/DerivedData/GlueDemo/Build/Intermediates/Glue.build/Debug-iphonesimulator/GlueTests.build/Objects-normal/x86_64/AFHTTPRequestOperationManager.gcno
./demo/glue-ios/DerivedData/GlueDemo/Build/Intermediates/Glue.build/Debug-iphonesimulator/GlueTests.build/Objects-normal/x86_64/AFHTTPSessionManager.gcno
./demo/glue-ios/DerivedData/GlueDemo/Build/Intermediates/Glue.build/Debug-iphonesimulator/GlueTests.build/Objects-normal/x86_64/AFNetworkReachabilityManager.gcno
./demo/glue-ios/DerivedData/GlueDemo/Build/Intermediates/Glue.build/Debug-iphonesimulator/GlueTests.build/Objects-normal/x86_64/AFSecurityPolicy.gcno
./demo/glue-ios/DerivedData/GlueDemo/Build/Intermediates/Glue.build/Debug-iphonesimulator/GlueTests.build/Objects-normal/x86_64/AFURLConnectionOperation.gcno
./demo/glue-ios/DerivedData/GlueDemo/Build/Intermediates/Glue.build/Debug-iphonesimulator/GlueTests.build/Objects-normal/x86_64/AFURLRequestSerialization.gcno
./demo/glue-ios/DerivedData/GlueDemo/Build/Intermediates/Glue.build/Debug-iphonesimulator/GlueTests.build/Objects-normal/x86_64/AFURLResponseSerialization.gcno
./demo/glue-ios/DerivedData/GlueDemo/Build/Intermediates/Glue.build/Debug-iphonesimulator/GlueTests.build/Objects-normal/x86_64/AFURLSessionManager.gcno
./demo/glue-ios/DerivedData/GlueDemo/Build/Intermediates/Glue.build/Debug-iphonesimulator/GlueTests.build/Objects-normal/x86_64/GUHTTPTest.gcno
./demo/glue-ios/DerivedData/GlueDemo/Build/Intermediates/Glue.build/Debug-iphonesimulator/GlueTests.build/Objects-normal/x86_64/GUHTTPTestResponse.gcno
./demo/glue-ios/DerivedData/GlueDemo/Build/Intermediates/Glue.build/Debug-iphonesimulator/GlueTests.build/Objects-normal/x86_64/GUServerTests.gcno
./demo/glue-ios/DerivedData/GlueDemo/Build/Intermediates/Glue.build/Debug-iphonesimulator/GlueTests.build/Objects-normal/x86_64/ServerTestCase.gcno
./demo/glue-ios/DerivedData/GlueDemo/Build/Intermediates/Glue.build/Debug-iphonesimulator/GlueTests.build/Objects-normal/x86_64/WebViewTestCase.gcno
Keiths-MBP-2:glue keith$ find . -name \*.gcda
./demo/glue-ios/DerivedData/GlueDemo/Build/Intermediates/Glue.build/Debug-iphonesimulator/GlueTests.build/Objects-normal/x86_64/AFHTTPRequestOperation.gcda
./demo/glue-ios/DerivedData/GlueDemo/Build/Intermediates/Glue.build/Debug-iphonesimulator/GlueTests.build/Objects-normal/x86_64/AFHTTPRequestOperationManager.gcda
./demo/glue-ios/DerivedData/GlueDemo/Build/Intermediates/Glue.build/Debug-iphonesimulator/GlueTests.build/Objects-normal/x86_64/AFHTTPSessionManager.gcda
./demo/glue-ios/DerivedData/GlueDemo/Build/Intermediates/Glue.build/Debug-iphonesimulator/GlueTests.build/Objects-normal/x86_64/AFNetworkReachabilityManager.gcda
./demo/glue-ios/DerivedData/GlueDemo/Build/Intermediates/Glue.build/Debug-iphonesimulator/GlueTests.build/Objects-normal/x86_64/AFSecurityPolicy.gcda
./demo/glue-ios/DerivedData/GlueDemo/Build/Intermediates/Glue.build/Debug-iphonesimulator/GlueTests.build/Objects-normal/x86_64/AFURLConnectionOperation.gcda
./demo/glue-ios/DerivedData/GlueDemo/Build/Intermediates/Glue.build/Debug-iphonesimulator/GlueTests.build/Objects-normal/x86_64/AFURLRequestSerialization.gcda
./demo/glue-ios/DerivedData/GlueDemo/Build/Intermediates/Glue.build/Debug-iphonesimulator/GlueTests.build/Objects-normal/x86_64/AFURLResponseSerialization.gcda
./demo/glue-ios/DerivedData/GlueDemo/Build/Intermediates/Glue.build/Debug-iphonesimulator/GlueTests.build/Objects-normal/x86_64/AFURLSessionManager.gcda
./demo/glue-ios/DerivedData/GlueDemo/Build/Intermediates/Glue.build/Debug-iphonesimulator/GlueTests.build/Objects-normal/x86_64/GUHTTPTest.gcda
./demo/glue-ios/DerivedData/GlueDemo/Build/Intermediates/Glue.build/Debug-iphonesimulator/GlueTests.build/Objects-normal/x86_64/GUHTTPTestResponse.gcda
./demo/glue-ios/DerivedData/GlueDemo/Build/Intermediates/Glue.build/Debug-iphonesimulator/GlueTests.build/Objects-normal/x86_64/GUServerTests.gcda
./demo/glue-ios/DerivedData/GlueDemo/Build/Intermediates/Glue.build/Debug-iphonesimulator/GlueTests.build/Objects-normal/x86_64/ServerTestCase.gcda
./demo/glue-ios/DerivedData/GlueDemo/Build/Intermediates/Glue.build/Debug-iphonesimulator/GlueTests.build/Objects-normal/x86_64/WebViewTestCase.gcda
```

**Comment by keithkml** [comment]
I just found the command-line help and tried this, but I'm getting the same error:

```
Keiths-MBP-2:glue keith$ groovy http://frankencover.it/with -s src/ios/objc/ -p ./demo/glue-ios/DerivedData/ -d
setting custom dir to ./demo/glue-ios/DerivedData/

▸ Code Coverage src/ios/objc/
#!/bin/sh
mkdir -p build/reports/temp/coverage-data-collate
mkdir -p build/reports/temp/coverage-data
find ./demo/glue-ios/DerivedData/ -name Camera.gcno -o -name Camera.gcda -o -name FlashBrightnessHandler.gcno -o -name FlashBrightnessHandler.gcda -o -name Glue-objc.gcno -o -name Glue-objc.gcda -o -name Glue.gcno -o -name Glue.gcda -o -name WCWebViewController.gcno -o -name WCWebViewController.gcda | rsync --files-from=- / build/reports/temp/coverage-data-collate
find build/reports/temp/coverage-data-collate -type file -exec cp -fr {} build/reports/temp/coverage-data \;
rm -fr build/reports/temp/coverage-data-collate
geninfo build/reports/temp/coverage-data/*.gcno --no-recursion --output-filename build/reports/temp/coverage.info.temp
lcov -r build/reports/temp/coverage.info.temp main.m queue.h once.h CGGeometry.h MKGeometry.h NSRange.h > build/reports/temp/coverage.info
genhtml --no-function-coverage --no-branch-coverage -o /Users/keith/Code/glue/glue/build/reports/coverage --prefix /Users/keith/Code/glue/glue/src/ios/objc/ build/reports/temp/coverage.info
            
Caught: java.lang.RuntimeException: 

✗ Coverage data not found
    ☐ To see how to set build flags, visit http://frankencover.it
    ☐ Exercise your code with tests or otherwise.
    ☐ Run this script again.


java.lang.RuntimeException: 

✗ Coverage data not found
    ☐ To see how to set build flags, visit http://frankencover.it
    ☐ Exercise your code with tests or otherwise.
    ☐ Run this script again.


	at ReportParser.<init>(with:203)
	at ReportGenerator.printSummary(with:166)
	at ReportGenerator.generate(with:153)
	at ReportGenerator$generate.call(Unknown Source)
	at FrankenCliReader.execute(with:62)
	at FrankenCliReader$execute.call(Unknown Source)
	at with.run(with:13)
```

**Comment by siddharthan64** [comment]
Hi
 Check out the path for the coverage info file. Point it to the folder
where the .xcodproj file sits. I had the same issue.

**Comment by keithkml** [comment]
Hi @siddharthan64 - what do you mean "point it"? With -p? Or -s?

**Comment by alexargo** [comment]
I've been having the same issue. Can you elaborate, siddharthan64? Are you talking about using -p(roducts-dir) command line switch? I've tried pointing that to my DerivedData folder, to the folders with the actual .gcno files, tried removing any specific options and letting it use the "IDE defaults". None of that has worked for me.

**Comment by jasperblues** [comment]
@siddharthan64 Actually I mentioned in abother issue that it's definitely not necessary to point at the XcodeProj dir, I don't know why this worked for you. 

@keithkml, you're on the right track. But can you try using the fully expanded path as the -p arg, not with the ./ in it? Suspect it might not be expanding the other properly. 

Also what version of lcov and xcode do you have?

**Comment by alexargo** [comment]
@jasperblues Here's two scripts I'm attempting to use, but get the same error on both:

https://gist.github.com/alexargo/245d09f2dc527053d5df

**Comment by jasperblues** [comment]
Hmm. I have lcov 1.11. There's were earlier versions that didn't like clang/llvm, not sure the exact version that was fixed. 

Can you try checking out Typhoon and running the build.sh script there? That will indicate if we have a general or project specific problems.

**Comment by alexargo** [comment]
Typhoon fails with the same error. I just checked it out, installed the dependencies listed by the build script, and ran build.sh: https://gist.github.com/alexargo/260e4edc7a667acac9bc

**Comment by alexargo** [comment]
Updated to lcov 1.11 and both Typhoon and my project now works. 1.10 was literally the version that I got when doing a brew install lcov a few days ago... this was an install of brew that hadn't been updated for a while however. @keithkml @siddharthan64  What version of lcov are you guys using?

**Comment by jasperblues** [comment]
@alexargo Thanks very much for the info. I'll update the website with a notice that lcov 1.11 is strictly required for Xcode 6.x. 

Are you able to install lcov 1.11 through brew?

**Comment by alexargo** [comment]
Yeah as long as you get the latest. I installed brew a couple months ago and hadn't touched it on this ci machine which is why I got an older version originally.

**Comment by jasperblues** [comment]
OK, that's good.

**Comment by alexargo** [comment]
Hmmm... i'm noticing something else weird... it's not actually putting output where it says it will when I use it on my project. Your build script for typhon is outputting the report however. I attempted to specify the output directory and get the same error that is listed above. I'm not sure if this is the same issue or a separate issue... same error... different cause? (Don't judge my code coverage... that's why I'm trying to get this working :) )

Alexs-Mac-mini:Common Alex$ groovy http://frankencover.it/with --source-dir "${PWD}/Common"

▸ Code Coverage /Users/Alex/Code/jenkins/workspace/LibCommon(iOS)/Libraries/ObjectiveC/Common/Common/
    ✗ lines........: 6.4% (376 of 5845 lines)
   📊  full report..: build/reports/coverage/index.html

Alexs-Mac-mini:Common Alex$ ls build/reports/
junit.xml
Alexs-Mac-mini:Common Alex$ groovy http://frankencover.it/with --source-dir "${PWD}/Common" --output-dir "${PWD}/build"

▸ Code Coverage /Users/Alex/Code/jenkins/workspace/LibCommon(iOS)/Libraries/ObjectiveC/Common/Common/
Caught: java.lang.RuntimeException: 

✗ Coverage data not found
    ☐ To see how to set build flags, visit http://frankencover.it
    ☐ Exercise your code with tests or otherwise.
    ☐ Run this script again.


java.lang.RuntimeException: 

✗ Coverage data not found
    ☐ To see how to set build flags, visit http://frankencover.it
    ☐ Exercise your code with tests or otherwise.
    ☐ Run this script again.


	at ReportParser.<init>(with:203)
	at ReportGenerator.printSummary(with:166)
	at ReportGenerator.generate(with:153)
	at ReportGenerator$generate.call(Unknown Source)
	at FrankenCliReader.execute(with:62)
	at FrankenCliReader$execute.call(Unknown Source)
	at with.run(with:13)

**Comment by jasperblues** [comment]
Does `${PWD}/build` exist beforehand?

**Comment by jasperblues** [comment]
Added note to site that lcov 1.11 is required. @alexargo, can you open a separate issue for the output directory?

**Comment by jasperblues** [comment]
@keithkml Confirm that upgrading lcov also fixes the issue for you? 

@alexargo Coverage cops are on the way ;)
